#!/usr/bin/env bash

# ensure tests are passing in both python 2 and 3
{ echo "Testing with python3" ; python3 -m unittest discover; } \
 && { echo "Testing with python2" ; python2 -3 -m unittest discover; }
